name: Update Naukri Profile

on:
  workflow_dispatch:

jobs:
  update-profile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Update Naukri profile
        uses: Prateek-Wayne/naukri-resume-action@main
        with:
          username: ${{ secrets.NAUKRI_USERNAME }}
          password: ${{ secrets.NAUKRI_PASSWORD }}
          profile_id: ${{ secrets.NAUKRI_PROFILE_ID }}
          resume_path: |-
            ./home/sai-exflow/nakuri/Naukri-resume-action/resumes/BeeraSaikumar-Resume.pdf/home/sai-exflow/nakuri/Naukri-resume-action/resumes/BeeraSaikumar-Resume.pdf
          profile_summary: 'SOC Analyst with 4.5+ years of experience in security monitoring,
                            SIEM, Splunk, QRadar, CrowdStrike Falcon, Microsoft Sentinel,
                            incident response, threat hunting, vulnerability management,
                            and log analysis across enterprise environments' # Optional: min 50 chars
          resume_headline: 'SOC Analyst | Splunk | QRadar | CrowdStrike | Microsoft Sentinel |Incident Response | 4.8+ Years' # Optional: max 250 chars
